name: Deploy
on:
  push:
    tags:
      - "*"

jobs:
  tag:
    name: Deploy Wordpress Plugin
    runs-on: ubuntu-latest
    steps:
      - name: deploy plugin
      - uses: 10up/action-wordpress-plugin-deploy@stable
    env:
      SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
      SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      SLUG: komoju-japanese-payments
