name: lint

on:
  - pull_request
  - push

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@2.4.0
        with:
          extensions: curl
      - name: Setup dependencies
        run: |
          which php
          which composer
          php -i
          composer
          composer install
      - name: Run lint
        run: ./vendor/bin/php-cs-fixer fix --dry-run
